### PR TITLE
annotating L4-DRG as a generic DRG

### PR DESCRIPTION
**Pull request by napakalas**
With this PR, L4-DRG is annotated as a generic DRG. This will solve a problem of dataset searching annotated with DRG.

### CODE REVIEW

**Comment by dbrnz** [comment]
@napakalas what happens to paths that involve `L4-DRG`? They will not be able to find the feature.

I understood that we are going to specify (in JSON) that `L4-DRG` is a proxy for `DRG`, to be used when placing markers -- do you recall the discussion? @nickerso should this commit be reverted? It's going to break neuron path routing...

Going forward, would it be sensible to require a review stage for the merging of PRs?

**Comment by napakalas** [comment]
In this update, I added double annotations, such as in the liver and kidney, so L4-DRG retains the previous annotation while adding a new annotation as a generic DRG. Paths involving the L4-DRG can still locate it. I’ve attached two screenshots: the first shows the state before the addition, and the second shows it after. There are three paths passing through the L4-DRG, all of which are rendered correctly after adding the annotation. Those paths are:
- ilxtr:neuron-type-sdcol-c
- ilxtr:sparc-nlp/femrep/60
- ilxtr:sparc-nlp/femrep/61

Before addition
After addition

**Comment by dbrnz** [comment]
> adding a new annotation as a generic DRG

Do you mean adding a new feature (presumably drawn to match L4-DRG which has been annotated as DRG??

**Comment by napakalas** [comment]
Yes, so now the searching with the terms `UBERON:0003943 `(fourth lumbar dorsal root ganglion) or `UBERON:0000044` (dorsal root ganglion) will highlight the same location.

**Comment by dbrnz** [comment]
`Yes` meaning you have two features on top of each other? Or `yes` meaning that searching with either term will highlight the same location??

This isn't a particularly clean "hack" (for all sorts of reasons)... Wouldn't it be better to wait until the proxy mechanism is in place (which should be by the end of next week)?? Then this representative DRG feature should be removed.

**Pull request merged**
